version: '3.9'

services:
  drupal:
    image: drupal:9
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
    ports:
      - "8080:80"
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=DrupalPass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"     
volumes:
  modules:
  profiles:
  themes:
  sites:
  pagdata: