# This example file from a previous lecture where we ran drupal in docker compose
# in this Assignment, change it to work with the default drupal image, and change
# postgres to use a Swarm secret. More info in the README.md file.
version: "3.9"
services:
  drupal:
    image: drupal:9
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
 
  postgres:
    image: postgres:14
    secrets:
      - psql_user
      - psql_password
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql_user:
    external: true
  psql_password:
    external: true

# Building the secrets in the stack using the CLI:
# echo "drupal" | docker secret create psql_user -
# echo "drupalPass" | docker secret create psql_password -

# Then deploying the stack using the CLI:
# docker stack deploy -c docker-compose.yml drupal_stack